# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-22 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_auto_20190121_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderinfo',
            old_name='trade_status',
            new_name='pay_trade_status',
        ),
        migrations.RenameField(
            model_name='orderinfo',
            old_name='signing_mobile',
            new_name='signer_mobile',
        ),
        migrations.RenameField(
            model_name='orderinfo',
            old_name='signing_name',
            new_name='signer_name',
        ),
        migrations.AlterField(
            model_name='ordergoods',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='trade.OrderInfo', verbose_name='所属订单'),
        ),
    ]
