# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-22 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0007_auto_20190122_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='address',
            field=models.CharField(max_length=200, verbose_name='收货地址'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='signer_mobile',
            field=models.CharField(max_length=11, verbose_name='联系电话'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='signer_name',
            field=models.CharField(max_length=30, verbose_name='签收人'),
        ),
    ]
