# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-21 20:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_auto_20190121_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='signing_mobile',
            new_name='signer_mobile',
        ),
        migrations.RenameField(
            model_name='useraddress',
            old_name='signing_name',
            new_name='signer_name',
        ),
    ]
